#BD POSTGRESS
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/factura
    password: 12345
    username: postgres

#JPA-HIBERNATE
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: create-drop

#TAMANIO DE LA FOTO
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


#SWAGGER
